name: "Camera Fix Report"
description: "Let us know if the module worked or not on your OnePlus 13T with OxygenOS."
title: "[Report] Camera Fix - Working or Not Working"
labels: ["report", "feedback"]
body:
  - type: dropdown
    id: status
    attributes:
      label: "Did the module work for you?"
      options:
        - "Yes, it worked (Working)"
        - "No, it did not work (Not Working)"
      description: "Select whether the camera fix worked on your device."
    validations:
      required: true

  - type: textarea
    id: device-info
    attributes:
      label: "Device Info"
      description: "Example: OnePlus 13T 12GB/256GB"
    validations:
      required: true

  - type: textarea
    id: oxygenos-version
    attributes:
      label: "OxygenOS Version"
      description: "Example: OxygenOS 15.0.0.3.GM21AA"
    validations:
      required: false

  - type: dropdown
    id: bootloader
    attributes:
      label: "Bootloader Status"
      options:
        - "Unlocked"
        - "Locked"
      description: "Was your bootloader unlocked when applying the module?"
    validations:
      required: false

  - type: dropdown
    id: root
    attributes:
      label: "Root Access (Magisk, etc.)"
      options:
        - "Yes, Magisk installed"
        - "No, not rooted"
      description: "Did you have root access when applying the module?"
    validations:
      required: false

  - type: textarea
    id: symptoms
    attributes:
      label: "Issues Fixed or Still Present"
      description: "Be specific – e.g., Camera not launching, battery not reported correctly, etc."
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "Additional Info"
      description: "Mention other modules, custom kernels, or anything else that might be relevant."
    validations:
      required: false