name: "Camera Fix Report"
description: "Let us know if the module worked or not on your OnePlus 13T with OxygenOS."
title: "[Report] Camera Fix - Working or Not Working"
labels: ["report", "feedback"]
body:
  - type: dropdown
    id: status
    attributes:
      label: "Did the module work for you?"
      options:
        - "Working"
        - "Not Working"
      description: "Select whether the camera fix worked on your device."
    validations:
      required: true

  - type: dropdown
    id: device-info
    attributes:
      label: "Device Info"
      options:
        - "OnePlus 13T 12GB/256GB"
        - "OnePlus 13T 12GB/512GB"
        - "OnePlus 13T 16GB/256GB"
        - "OnePlus 13T 16GB/512GB"
        - "OnePlus 13T 16GB/1TB"
      description: "Select your device model and RAM/Storage configuration."
    validations:
      required: true

  - type: dropdown
    id: device-color
    attributes:
      label: "Device Color"
      options:
        - "Black"
        - "Pink"
        - "Silver"
      description: "Select your device color."
    validations:
      required: true

  - type: dropdown
    id: oxygenos-version
    attributes:
      label: "OxygenOS Version"
      options:
        - "OxygenOS CPH2723_15.0.2.302"
        - "OxygenOS CPH2723_15.0.2.303"
        - "OxygenOS CPH2723_15.0.2.400"
      description: "Select your OxygenOS version."
    validations:
      required: true

  - type: dropdown
    id: root-manager
    attributes:
      label: "Root Manager Used"
      options:
        - "Magisk"
        - "Magisk Alpha"
        - "Apatch"
        - "KernelSU"
        - "KernelSU-Next"
        - "Other (Please specify in the Additional Info section)"
      description: "Select the root manager you used to apply the module."
    validations:
      required: true

  - type: textarea
    id: symptoms
    attributes:
      label: "Symptoms"
      description: "Describe the symptoms you experienced with the module."
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: "Additional Info"
      description: "Mention other modules, custom kernels, or anything else that might be relevant."
    validations:
      required: false